name: Go workflow
"on": 
  push:
    paths:
      - .github/workflows/setupgo.yml



jobs:
  build:
    name: Setup Go action
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-b