name: Go workflow
"on": 
  push:
    paths:
      - .github/workflows/setupgo.yml
      -  action-b/hello.go
      - Makefile
      - action-b/build-and-push.sh



jobs:
  build:
    name: Setup Go action
    runs-on: [ "self-hosted" ]
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login docker.io
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          
      - name: Build && Push
        run:
          make build.go-app
