name: Go workflow
on: push

jobs:
  build:
    name: Setup Go action
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.9.3' # The Go version to download (if necessary) and use.
      - run: go run hello.go
