name: Go workflow
"on": 
  push:
    paths:
      - .github/workflows/setupgo.yml
      -  action-b/hello.go



jobs:
  build:
    name: Setup Go action
    runs-on: [ "self-hosted" ]
    
    steps:
      - uses: actions/checkout@v2

      - name: Build && Push
        run:
          docker build -t arosilier/hello:v1 .
